name: Build and upload to PyPI

# Build on every branch push, tag push, and pull request change:
on: [push, pull_request]

jobs:
  build_linux_wheels:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ""
          auto-activate-base: true
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
      - name: Install wheel
        run: conda install wheel opencv numpy cython

      # - name: Build manylinux Python wheels
      # - uses: RalfG/python-wheels-manylinux-build@v0.3.4-manylinux2010_x86_64
      #   with:
      #     python-versions: 'cp36-cp36m cp37-cp37m cp38'
      #     build-requirements: 'cython numpy opencv'

      # - uses: actions/upload-artifact@v2
      #   with:
      #     path: dist/*-manylinux*.whl

  # upload_pypi_manylinux:
  #   needs: [build_linux_wheels]
  #   runs-on: ubuntu-latest
  #   if: startsWith(github.event.ref, 'refs/tags') || github.event_name == 'release'
  #   steps:
  #     - uses: actions/download-artifact@v2
  #       with:
  #         name: artifact
  #         path: dist

  #     - uses: pypa/gh-action-pypi-publish@v1.4.2
  #       with:
  #         user: __token__
  #         password: ${{ secrets.PYPI_API_TOKEN }}
